# Generated by Django 2.2.12 on 2022-02-07 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneyManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
