# Generated by Django 2.2.12 on 2022-02-12 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyManage', '0003_auto_20220211_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.date(2022, 2, 12)),
        ),
    ]
